CREATE TABLE roles (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name        VARCHAR(30)  NOT NULL,
                       description VARCHAR(255),
                       CONSTRAINT pk_roles PRIMARY KEY (id),
                       CONSTRAINT uq_roles_name UNIQUE (name),
                       CONSTRAINT ck_roles_name CHECK (name IN ('ADMIN', 'MANAGER', 'EMPLOYEE'))
);

INSERT INTO roles (name, description) VALUES
                                          ('ADMIN', 'Full access to the platform'),
                                          ('MANAGER', 'Commercial management and reports'),
                                          ('EMPLOYEE', 'Limited access: consult data and create orders');