CREATE TABLE users (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       first_name VARCHAR(100) NOT NULL,
                       last_name  VARCHAR(100) NOT NULL,
                       email      VARCHAR(255) NOT NULL,
                       password   VARCHAR(255) NOT NULL,
                       phone      VARCHAR(20),
                       status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
                       role_id    BIGINT       NOT NULL,
                       created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
                       updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uq_users_email UNIQUE (email),
                       CONSTRAINT fk_users_roles FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
                       CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_users_role_id ON users (role_id);