CREATE TABLE customers (
                           id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           first_name VARCHAR(100) NOT NULL,
                           last_name  VARCHAR(100) NOT NULL,
                           email      VARCHAR(255) NOT NULL,
                           phone      VARCHAR(20),
                           address    VARCHAR(255),
                           company    VARCHAR(150),
                           tax_number VARCHAR(50),
                           status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
                           created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
                           updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
                           CONSTRAINT pk_customers PRIMARY KEY (id),
                           CONSTRAINT uq_customers_email UNIQUE (email),
                           CONSTRAINT ck_customers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX uq_customers_tax_number
    ON customers (tax_number)
    WHERE tax_number IS NOT NULL;