CREATE TABLE categories (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            name        VARCHAR(100) NOT NULL,
                            description VARCHAR(255),
                            parent_id   BIGINT,
                            created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                            updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                            CONSTRAINT pk_categories PRIMARY KEY (id),
                            CONSTRAINT uq_categories_name UNIQUE (name),
                            CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE RESTRICT,
                            CONSTRAINT ck_categories_parent_not_self CHECK (parent_id <> id)
);

CREATE INDEX idx_categories_parent_id ON categories (parent_id);