CREATE TABLE products (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          reference      VARCHAR(50)   NOT NULL,
                          name           VARCHAR(200)  NOT NULL,
                          description    TEXT,
                          purchase_price NUMERIC(14,3) NOT NULL,
                          selling_price  NUMERIC(14,3) NOT NULL,
                          quantity       INTEGER       NOT NULL DEFAULT 0,
                          minimum_stock  INTEGER       NOT NULL DEFAULT 0,
                          category_id    BIGINT        NOT NULL,
                          status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
                          version        BIGINT        NOT NULL DEFAULT 0,
                          created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
                          updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
                          CONSTRAINT pk_products PRIMARY KEY (id),
                          CONSTRAINT uq_products_reference UNIQUE (reference),
                          CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
                          CONSTRAINT ck_products_purchase_price CHECK (purchase_price > 0),
                          CONSTRAINT ck_products_selling_price CHECK (selling_price > 0),
                          CONSTRAINT ck_products_quantity CHECK (quantity >= 0),
                          CONSTRAINT ck_products_minimum_stock CHECK (minimum_stock >= 0),
                          CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_status ON products (status);